# Generated By: Cursor (Claude)
"""
Configuration management for MCP GitHub server.
"""

import os
import yaml
import logging
from dataclasses import dataclass
from typing import Optional, Dict, Any


@dataclass
class GitHubConfig:
    """GitHub API configuration."""
    token: Optional[str] = None
    base_url: str = "https://api.github.com"
    timeout: int = 30
    rate_limit_delay: float = 1.0


@dataclass
class LoggingConfig:
    """Logging configuration."""
    level: str = "INFO"
    format: str = "%(asctime)s - %(levelname)s - %(message)s"


@dataclass
class ServerConfig:
    """Complete MCP server configuration."""
    github: GitHubConfig
    logging: LoggingConfig

    @classmethod
    def from_dict(cls, config_dict: Dict[str, Any]) -> 'ServerConfig':
        """Create ServerConfig from dictionary."""
        github_config = GitHubConfig(**config_dict.get('github', {}))
        logging_config = LoggingConfig(**config_dict.get('logging', {}))
        return cls(github=github_config, logging=logging_config)

    @classmethod
    def from_file(cls, config_path: str) -> 'ServerConfig':
        """Load configuration from YAML file."""
        try:
            with open(config_path, 'r') as f:
                config_dict = yaml.safe_load(f)
            return cls.from_dict(config_dict)
        except FileNotFoundError:
            logging.warning(f"Config file {config_path} not found, using defaults")
            return cls.from_dict({})
        except yaml.YAMLError as e:
            logging.error(f"Error parsing config file {config_path}: {e}")
            raise

    @classmethod
    def from_env(cls) -> 'ServerConfig':
        """Create configuration from environment variables."""
        github_config = GitHubConfig(
            token=os.getenv("GITHUB_TOKEN") or os.getenv("GITHUB_BEARER_TOKEN"),
            base_url=os.getenv("GITHUB_BASE_URL", "https://api.github.com"),
            timeout=int(os.getenv("GITHUB_TIMEOUT", "30")),
            rate_limit_delay=float(os.getenv("GITHUB_RATE_LIMIT_DELAY", "1.0"))
        )

        logging_config = LoggingConfig(
            level=os.getenv("LOG_LEVEL", "INFO"),
            format=os.getenv("LOG_FORMAT",
                           "%(asctime)s - %(levelname)s - %(message)s")
        )

        return cls(github=github_config, logging=logging_config)

    def configure_logging(self) -> None:
        """Configure logging based on settings."""
        logging.basicConfig(
            level=getattr(logging, self.logging.level.upper(), logging.INFO),
            format=self.logging.format,
            force=True  # Override any existing logging config
        )


def load_config(config_path: Optional[str] = None) -> ServerConfig:
    """
    Load configuration with fallback priority:
    1. Explicit config file path
    2. Environment variable MCP_GITHUB_CONFIG
    3. mcp_github_server.yaml in current directory
    4. Environment variables only
    """
    if config_path:
        return ServerConfig.from_file(config_path)

    # Check environment variable
    env_config_path = os.getenv("MCP_GITHUB_CONFIG")
    if env_config_path:
        return ServerConfig.from_file(env_config_path)

    # Check default file location
    default_config = "mcp_github_server.yaml"
    if os.path.exists(default_config):
        return ServerConfig.from_file(default_config)

    # Fall back to environment variables
    logging.info("No config file found, using environment variables")
    return ServerConfig.from_env()
