# Generated By: Cursor (Claude)
"""
GitHub API client adapted from gh-pulls-summary tool.

This module reuses core GitHub API integration logic from the original
gh-pulls-summary CLI tool, adapted for MCP server architecture.
"""

import requests
import logging
import subprocess
from typing import Dict, Any, Optional, List


# Custom Exception Classes
class MissingRepoError(Exception):
    """Raised when repository information cannot be determined."""
    pass


class GitHubAPIError(Exception):
    """Raised when GitHub API requests fail."""
    def __init__(self, message, status_code=None, response_text=None):
        self.status_code = status_code
        self.response_text = response_text
        super().__init__(message)


class RateLimitError(GitHubAPIError):
    """Raised when GitHub API rate limit is exceeded."""
    pass


class NetworkError(Exception):
    """Raised when network-related errors occur."""
    pass


class ValidationError(Exception):
    """Raised when input validation fails."""
    pass


class GitHubClient:
    """GitHub API client with authentication and rate limiting."""
    
    def __init__(self, token: Optional[str] = None,
                 base_url: str = "https://api.github.com",
                 timeout: int = 30, rate_limit_delay: float = 1.0):
        self.base_url = base_url
        self.timeout = timeout
        self.rate_limit_delay = rate_limit_delay
        # Set up headers
        self.headers = {
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28"
        }

        # Add authentication if token provided
        if token:
            self.headers["Authorization"] = f"Bearer {token}"
    
    def request(self, endpoint: str, params: Optional[Dict] = None,
                 use_paging: bool = True) -> Any:
        """
        Makes a GitHub API request and optionally handles pagination.
        Returns all results across all pages if pagination is enabled.
        Returns None if no results are found or an error occurs.
        """
        if params is None:
            params = {}

        all_results = []
        page = 1
        last_results = None  # Fail-safe to detect duplicate results

        while True:
            if use_paging:
                params["page"] = page
            url = f"{self.base_url}{endpoint}"
            logging.debug(f"Making API request to {url} with params {params}")
            
            try:
                response = requests.get(url, headers=self.headers,
                                       params=params, timeout=self.timeout)
            except requests.exceptions.ConnectionError as e:
                raise NetworkError(
                    f"Network connection failed. Please check your internet "
                    f"connection and try again. Details: {e}")
            except requests.exceptions.Timeout as e:
                raise NetworkError(
                    f"Request timed out. The GitHub API may be slow. "
                    f"Please try again. Details: {e}")
            except requests.exceptions.RequestException as e:
                raise NetworkError(
                    f"Network error occurred while contacting GitHub API. "
                    f"Details: {e}")

            if (response.status_code == 403 and
                    "X-RateLimit-Remaining" in response.headers and
                    response.headers["X-RateLimit-Remaining"] == "0"):
                reset_time = response.headers.get("X-RateLimit-Reset", "unknown")
                raise RateLimitError(
                    f"GitHub API rate limit exceeded. "
                    f"Rate limit will reset at {reset_time}. "
                    f"Consider using a GitHub token to increase your rate limit "
                    f"(5000 requests/hour vs 60 requests/hour). "
                    f"Set the GITHUB_TOKEN environment variable with a personal "
                    f"access token."
                )
            
            if response.status_code == 401:
                raise GitHubAPIError(
                    "GitHub API authentication failed. Please check your "
                    "GITHUB_TOKEN if set. You may need to generate a new "
                    "personal access token from GitHub Settings.",
                    status_code=401,
                    response_text=response.text
                )
            
            if response.status_code == 404:
                raise GitHubAPIError(
                    f"GitHub API endpoint not found: {endpoint}. "
                    f"Please verify the repository owner and name are correct.",
                    status_code=404,
                    response_text=response.text
                )
            
            if response.status_code != 200:
                raise GitHubAPIError(
                    f"GitHub API request failed with status "
                    f"{response.status_code}. Endpoint: {endpoint}. "
                    f"Response: {response.text}",
                    status_code=response.status_code,
                    response_text=response.text
                )

            try:
                results = response.json()
            except ValueError as e:
                raise GitHubAPIError(
                    f"Invalid JSON response from GitHub API. The service may be "
                    f"experiencing issues. Details: {e}")

            if results == last_results:  # pragma: no cover
                logging.warning(
                    f"Duplicate results detected for pages {page-1} and {page}. "
                    f"This may indicate a GitHub API issue.")
                break

            # Handle cases where the response is a dictionary
            if isinstance(results, dict):
                logging.debug(f"Response is a dictionary: {results}")
                return results

            # Handle cases where the response is a list
            if not results or not use_paging:
                all_results.extend(results)
                break

            all_results.extend(results)
            last_results = results

            page += 1

        logging.debug(f"Fetched {len(all_results)} items from {endpoint}")
        return all_results

    def fetch_pull_requests(self, owner: str, repo: str,
                           state: str = "open") -> List[Dict[str, Any]]:
        """Fetches pull requests for the specified repository."""
        endpoint = f"/repos/{owner}/{repo}/pulls"
        params = {"state": state}
        logging.debug(f"Fetching '{state}' pull requests for {owner}/{repo}")
        return self.request(endpoint, params)

    def fetch_single_pull_request(self, owner: str, repo: str,
                                 pr_number: int) -> Dict[str, Any]:
        """Fetches a single pull request by its number."""
        endpoint = f"/repos/{owner}/{repo}/pulls/{pr_number}"
        logging.debug(f"Fetching single pull request #{pr_number} for {owner}/{repo}")
        return self.request(endpoint, use_paging=False)

    def fetch_issue_events(self, owner: str, repo: str,
                          issue_number: int) -> List[Dict[str, Any]]:
        """Fetches all issue events for a specific issue or pull request."""
        endpoint = f"/repos/{owner}/{repo}/issues/{issue_number}/events"
        logging.debug(f"Fetching issue events for issue #{issue_number} for {owner}/{repo}")
        return self.request(endpoint)

    def fetch_reviews(self, owner: str, repo: str,
                     pr_number: int) -> List[Dict[str, Any]]:
        """Fetches all reviews for a specific pull request."""
        endpoint = f"/repos/{owner}/{repo}/pulls/{pr_number}/reviews"
        logging.debug(f"Fetching reviews for PR #{pr_number} for {owner}/{repo}")
        return self.request(endpoint)
    
    def fetch_issues(self, owner: str, repo: str, state: str = "open",
                    labels: Optional[str] = None,
                    assignee: Optional[str] = None,
                    creator: Optional[str] = None) -> List[Dict[str, Any]]:
        """Fetches issues for the specified repository."""
        endpoint = f"/repos/{owner}/{repo}/issues"
        params = {"state": state}
        if labels:
            params["labels"] = labels
        if assignee:
            params["assignee"] = assignee
        if creator:
            params["creator"] = creator
        logging.debug(f"Fetching issues for {owner}/{repo}")
        return self.request(endpoint, params)
    
    def fetch_issue_comments(self, owner: str, repo: str,
                            issue_number: int) -> List[Dict[str, Any]]:
        """Fetches all comments for a specific issue."""
        endpoint = f"/repos/{owner}/{repo}/issues/{issue_number}/comments"
        logging.debug(f"Fetching comments for issue #{issue_number} for {owner}/{repo}")
        return self.request(endpoint)
    
    def fetch_pull_request_comments(self, owner: str, repo: str,
                                   pr_number: int) -> List[Dict[str, Any]]:
        """Fetches all review comments for a specific pull request."""
        endpoint = f"/repos/{owner}/{repo}/pulls/{pr_number}/comments"
        logging.debug(f"Fetching review comments for PR #{pr_number} for {owner}/{repo}")
        return self.request(endpoint)
    
    def fetch_file_content(self, owner: str, repo: str, path: str,
                          ref: Optional[str] = None) -> Dict[str, Any]:
        """Fetches content of a specific file."""
        endpoint = f"/repos/{owner}/{repo}/contents/{path}"
        params = {}
        if ref:
            params["ref"] = ref
        logging.debug(f"Fetching file content for {path} for {owner}/{repo}")
        return self.request(endpoint, params, use_paging=False)


def get_repo_and_owner_from_git() -> tuple[Optional[str], Optional[str]]:
    """
    Retrieves the repository and owner from the local Git configuration.
    Returns a tuple (owner, repo) or (None, None) if not found.
    """
    try:
        # Get the remote URL
        remote_url = subprocess.check_output(
            ["git", "config", "--get", "remote.origin.url"],
            stderr=subprocess.DEVNULL,
            text=True
        ).strip()

        # Parse the remote URL to extract owner and repo
        if remote_url.startswith("git@"):
            # SSH URL (e.g., git@github.com:owner/repo.git)
            _, path = remote_url.split(":", 1)
        elif remote_url.startswith("https://"):
            # HTTPS URL (e.g., https://github.com/owner/repo.git)
            # Split into up to 6 parts: ["https:", "", "domain", "owner",
            # "repo", "extra/path..."]
            parts = remote_url.split("/", 5)
            if len(parts) >= 5:
                path = f"{parts[3]}/{parts[4]}"  # owner/repo
            else:
                path = remote_url.split("/", 3)[-1]
        else:
            return None, None

        # Remove the `.git` suffix if present
        if path.endswith(".git"):
            path = path[:-4]

        owner, repo = path.split("/", 1)
        return owner, repo
    except Exception:  # pragma: no cover
        return None, None
