# Generated By: Cursor (Claude)
"""
MCP GitHub Server - Main entry point.

Provides GitHub repository analysis capabilities for AI coding assistants.
"""

import asyncio
import argparse
import logging
from typing import Any, Dict, List

try:
    from mcp.server import Server
    from mcp.types import Tool, TextContent
except ImportError:
    # For development without MCP installed
    logging.warning("MCP not available, running in development mode")
    Server = None
    Tool = None
    TextContent = None

from .config import load_config, ServerConfig
from .github_client import GitHubClient, get_repo_and_owner_from_git
from .tools.pull_request_tools import PullRequestTools
from .tools.issue_tools import IssueTools
from .tools.file_tools import FileTools


class MCPGitHubServer:
    """MCP GitHub Server implementation."""
    
    def __init__(self, config: ServerConfig):
        self.config = config
        self.config.configure_logging()
        
        # Initialize GitHub client
        self.github_client = GitHubClient(
            token=config.github.token,
            base_url=config.github.base_url,
            timeout=config.github.timeout,
            rate_limit_delay=config.github.rate_limit_delay
        )
        
        # Get repository context from local git
        self.default_owner, self.default_repo = get_repo_and_owner_from_git()
        if self.default_owner and self.default_repo:
            logging.info(f"Detected repository context: {self.default_owner}/{self.default_repo}")
        else:
            logging.warning("No git repository detected in current directory")
        
        # Initialize tool handlers
        self.pr_tools = PullRequestTools(self.github_client)
        self.issue_tools = IssueTools(self.github_client)
        self.file_tools = FileTools(self.github_client)
        
        # Initialize MCP server if available
        if Server:
            self.app = Server("mcp_github_server")
            self._setup_tools()
    
    def _setup_tools(self):
        """Register MCP tools."""
        if not self.app:
            return
            
        # Pull Request tools
        @self.app.list_tools()
        async def list_tools() -> List[Tool]:
            return [
                Tool(
                    name="search_pull_requests",
                    description="Search and filter pull requests in a repository. Returns a paginated list of PRs with basic metadata including title, state, author, creation date, and summary statistics. Supports filtering by state (open/closed/all) and limits results for performance.",
                    inputSchema={
                        "type": "object",
                        "properties": {
                            "owner": {"type": "string", "description": "Repository owner"},
                            "repo": {"type": "string", "description": "Repository name"},
                            "state": {"type": "string", "enum": ["open", "closed", "all"], "default": "open"},
                            "max_results": {"type": "integer", "minimum": 1, "maximum": 100, "default": 25}
                        },
                        "required": ["owner", "repo"]
                    }
                ),
                Tool(
                    name="get_pull_request_reviews",
                    description="Analyze pull request reviews and approval status with sophisticated state tracking. Handles complex review flows (approved → changes requested → approved) and returns latest review state per user, approval counts, change requests, and reviewer details. Essential for understanding PR readiness for merge.",
                    inputSchema={
                        "type": "object",
                        "properties": {
                            "owner": {"type": "string", "description": "Repository owner"},
                            "repo": {"type": "string", "description": "Repository name"},
                            "pr_number": {"type": "integer", "description": "Pull request number"}
                        },
                        "required": ["owner", "repo", "pr_number"]
                    }
                ),
                Tool(
                    name="get_pull_request_comments",
                    description="Retrieve all comments from a pull request including general comments, code review comments, and their resolution status. Supports filtering by resolution state (open/resolved/all) to focus on open discussions or get complete comment history for context analysis.",
                    inputSchema={
                        "type": "object",
                        "properties": {
                            "owner": {"type": "string", "description": "Repository owner"},
                            "repo": {"type": "string", "description": "Repository name"},
                            "pr_number": {"type": "integer", "description": "Pull request number"},
                            "resolution_filter": {"type": "string", "enum": ["all", "open", "resolved"], "default": "all"}
                        },
                        "required": ["owner", "repo", "pr_number"]
                    }
                ),
                Tool(
                    name="search_issues",
                    description="Search and filter issues within a repository with comprehensive filtering options. Returns paginated results with issue details including state, labels, assignees, creation dates, and activity. Supports filtering by state, labels, assignee, and creator for targeted issue analysis.",
                    inputSchema={
                        "type": "object",
                        "properties": {
                            "owner": {"type": "string", "description": "Repository owner"},
                            "repo": {"type": "string", "description": "Repository name"},
                            "state": {"type": "string", "enum": ["open", "closed", "all"], "default": "open"},
                            "labels": {"type": "string", "description": "Comma-separated labels"},
                            "assignee": {"type": "string", "description": "Assignee username"},
                            "creator": {"type": "string", "description": "Creator username"},
                            "max_results": {"type": "integer", "minimum": 1, "maximum": 100, "default": 25}
                        },
                        "required": ["owner", "repo"]
                    }
                ),
                Tool(
                    name="get_issue_comments",
                    description="Retrieve all comments from a specific issue for discussion analysis and context gathering. Returns complete comment thread with author information, timestamps, and content. Useful for understanding issue discussions and resolution progress.",
                    inputSchema={
                        "type": "object",
                        "properties": {
                            "owner": {"type": "string", "description": "Repository owner"},
                            "repo": {"type": "string", "description": "Repository name"},
                            "issue_number": {"type": "integer", "description": "Issue number"}
                        },
                        "required": ["owner", "repo", "issue_number"]
                    }
                ),
                Tool(
                    name="get_file_content",
                    description="Retrieve the raw content of files from a repository for code analysis and context. Supports specifying git references (branches, tags, commits) and optional line ranges for focused content retrieval. Essential for understanding codebase context when analyzing PRs or issues.",
                    inputSchema={
                        "type": "object",
                        "properties": {
                            "owner": {"type": "string", "description": "Repository owner"},
                            "repo": {"type": "string", "description": "Repository name"},
                            "path": {"type": "string", "description": "File path"},
                            "ref": {"type": "string", "description": "Branch/commit reference"}
                        },
                        "required": ["owner", "repo", "path"]
                    }
                )
            ]
        
        @self.app.call_tool()
        async def call_tool(name: str, arguments: Dict[str, Any]) -> List[TextContent]:
            """Handle tool calls."""
            try:
                # Fill in default owner/repo if not provided
                if "owner" not in arguments and self.default_owner:
                    arguments["owner"] = self.default_owner
                if "repo" not in arguments and self.default_repo:
                    arguments["repo"] = self.default_repo
                
                if name == "search_pull_requests":
                    result = await self.pr_tools.search_pull_requests(**arguments)
                elif name == "get_pull_request_reviews":
                    result = await self.pr_tools.get_pull_request_reviews(**arguments)
                elif name == "get_pull_request_comments":
                    result = await self.pr_tools.get_pull_request_comments(**arguments)
                elif name == "search_issues":
                    result = await self.issue_tools.search_issues(**arguments)
                elif name == "get_issue_comments":
                    result = await self.issue_tools.get_issue_comments(**arguments)
                elif name == "get_file_content":
                    result = await self.file_tools.get_file_content(**arguments)
                else:
                    raise ValueError(f"Unknown tool: {name}")
                
                return [TextContent(type="text", text=str(result))]
                
            except Exception as e:
                logging.error(f"Error calling tool {name}: {e}")
                return [TextContent(type="text", text=f"Error: {str(e)}")]

    async def run(self):
        """Run the MCP server."""
        if not self.app:
            logging.error("MCP server not available")
            return
            
        # Start the server
        from mcp.server.stdio import stdio_server
        async with stdio_server() as (read_stream, write_stream):
            await self.app.run(read_stream, write_stream, self.app.create_initialization_options())


def main():
    """Main entry point."""
    parser = argparse.ArgumentParser(description="MCP GitHub Server")
    parser.add_argument("--config", "-c", help="Path to configuration file")
    args = parser.parse_args()
    
    # Load configuration
    config = load_config(args.config)
    
    # Create and run server
    server = MCPGitHubServer(config)
    
    if Server:
        # Run as MCP server
        asyncio.run(server.run())
    else:
        # Development mode - just log that we're ready
        logging.info("MCP GitHub Server initialized (development mode - MCP not available)")
        print("Server ready. Install MCP dependencies to run as full MCP server.")


if __name__ == "__main__":
    main()