# Generated By: Cursor (Claude)
"""
File content tools for MCP GitHub server.
"""

import base64
import logging
from typing import Dict, Any, Optional
from ..github_client import GitHubClient


class FileTools:
    """Tools for repository file content retrieval."""

    def __init__(self, github_client: GitHubClient):
        self.client = github_client
    
    async def get_file_content(self, owner: str, repo: str, path: str,
                              ref: Optional[str] = None,
                              start_line: Optional[int] = None,
                              end_line: Optional[int] = None) -> Dict[str, Any]:
        """
        Retrieve repository file content with optional line ranges.

        For LLM context when analyzing PR changes.
        """
        try:
            # Fetch file content from GitHub
            file_data = self.client.fetch_file_content(owner, repo, path, ref)

            if not file_data:
                return {
                    "path": path,
                    "ref": ref,
                    "error": "File not found"
                }

            # Decode content if base64 encoded
            content = file_data.get("content", "")
            encoding = file_data.get("encoding", "")

            if encoding == "base64":
                try:
                    decoded_content = base64.b64decode(content).decode('utf-8')
                except UnicodeDecodeError:
                    # Handle binary files
                    return {
                        "path": path,
                        "ref": ref,
                        "type": "binary",
                        "size": file_data.get("size", 0),
                        "sha": file_data.get("sha", ""),
                        "url": file_data.get("html_url", "")
                    }
            else:
                decoded_content = content

            # Apply line range if specified
            if start_line is not None or end_line is not None:
                lines = decoded_content.split('\n')
                if start_line is not None:
                    start_idx = max(0, start_line - 1)
                else:
                    start_idx = 0

                if end_line is not None:
                    end_idx = min(len(lines), end_line)
                else:
                    end_idx = len(lines)

                selected_lines = lines[start_idx:end_idx]
                final_content = '\n'.join(selected_lines)

                # Add line numbers for context
                numbered_lines = []
                for i, line in enumerate(selected_lines,
                                        start=start_idx + 1):
                    numbered_lines.append(f"{i:6d}→{line}")
                numbered_content = '\n'.join(numbered_lines)
            else:
                final_content = decoded_content
                numbered_content = None

            return {
                "path": path,
                "ref": ref or "default",
                "type": "text",
                "content": final_content,
                "numbered_content": numbered_content,
                "size": len(final_content),
                "total_lines": len(decoded_content.split('\n')),
                "sha": file_data.get("sha", ""),
                "url": file_data.get("html_url", ""),
                "line_range": {
                    "start": start_line,
                    "end": end_line
                } if (start_line is not None or
                     end_line is not None) else None
            }

        except Exception as e:
            logging.error(f"Error getting file content: {e}")
            return {
                "path": path,
                "ref": ref,
                "error": str(e)
            }
