# Generated By: Cursor (Claude)
"""
Issue analysis tools for MCP GitHub server.
"""

import logging
from typing import Dict, Any, Optional
from ..github_client import GitHubClient


class IssueTools:
    """Tools for issue analysis and comment management."""

    def __init__(self, github_client: GitHubClient):
        self.client = github_client
    
    async def search_issues(self, owner: str, repo: str,
                           state: str = "open",
                           max_results: int = 25,
                           labels: Optional[str] = None,
                           assignee: Optional[str] = None,
                           creator: Optional[str] = None,
                           **kwargs) -> Dict[str, Any]:
        """
        Search issues in repository with state handling for latest
        assignee/label state.

        Handles complex state transitions like reopened issues, reassignments,
        label changes.
        """
        try:
            # Fetch issues from GitHub
            issues = self.client.fetch_issues(
                owner, repo, state=state, labels=labels,
                assignee=assignee, creator=creator
            )

            # Filter out pull requests (GitHub treats PRs as issues)
            actual_issues = [issue for issue in issues
                            if not issue.get("pull_request")]

            # Limit results
            limited_issues = actual_issues[:max_results]

            # Process each issue to get metadata
            processed_issues = []
            for issue in limited_issues:
                # Get comment count
                comments_count = issue.get("comments", 0)

                # Get current assignee(s) - GitHub API returns latest state
                assignees = [assignee["login"] for assignee in
                            issue.get("assignees", [])]

                # Get current labels - GitHub API returns latest state
                labels_list = [label["name"] for label in
                              issue.get("labels", [])]
                
                processed_issues.append({
                    "number": issue["number"],
                    "title": issue["title"],
                    "author": issue["user"]["login"],
                    "url": issue["html_url"],
                    "state": issue["state"],
                    "created_at": issue["created_at"],
                    "updated_at": issue["updated_at"],
                    "closed_at": issue.get("closed_at"),
                    "assignees": assignees,
                    "labels": labels_list,
                    "comments_count": comments_count,
                    "body": issue["body"] or ""
                })

            # Build pagination info
            has_next = len(actual_issues) > max_results

            return {
                "data": processed_issues,
                "pagination": {
                    "current_page": 1,
                    "has_next_page": has_next,
                    "per_page": max_results,
                    "total_count": len(actual_issues)
                }
            }

        except Exception as e:
            logging.error(f"Error searching issues: {e}")
            raise

    async def get_issue_comments(self, owner: str, repo: str,
                                issue_number: int) -> Dict[str, Any]:
        """
        Get all comments for specific issue.

        Returns comments with author, timestamp, and content.
        """
        try:
            # Fetch comments
            comments = self.client.fetch_issue_comments(owner, repo,
                                                        issue_number)

            if not comments:
                return {
                    "issue_number": issue_number,
                    "comments": [],
                    "total_comments": 0
                }

            # Process comments
            processed_comments = []
            for comment in comments:
                processed_comments.append({
                    "id": comment["id"],
                    "user": comment["user"]["login"],
                    "body": comment["body"],
                    "created_at": comment["created_at"],
                    "updated_at": comment["updated_at"],
                    "url": comment["html_url"]
                })

            # Sort by creation time
            processed_comments.sort(key=lambda c: c["created_at"])

            return {
                "issue_number": issue_number,
                "comments": processed_comments,
                "total_comments": len(processed_comments)
            }

        except Exception as e:
            logging.error(f"Error getting issue comments: {e}")
            raise
