# Generated By: Cursor (Claude)
"""
Pull request analysis tools for MCP GitHub server.

Reuses complex review state logic from gh-pulls-summary tool.
"""

import logging
from typing import Dict, Any, List
from ..github_client import GitHubClient


class PullRequestTools:
    """Tools for pull request analysis and review state management."""

    def __init__(self, github_client: GitHubClient):
        self.client = github_client
    
    async def search_pull_requests(self, owner: str, repo: str,
                                  state: str = "open",
                                  max_results: int = 25,
                                  **kwargs) -> Dict[str, Any]:
        """
        Search pull requests in repository.

        Returns paginated results with PR metadata, review counts, and approval status.
        """
        try:
            # Fetch PRs from GitHub
            prs = self.client.fetch_pull_requests(owner, repo, state)

            # Limit results
            limited_prs = prs[:max_results] if prs else []

            # Process each PR to get basic metadata
            processed_prs = []
            for pr in limited_prs:
                # Get basic review counts
                reviews = self.client.fetch_reviews(owner, repo, pr["number"])
                review_summary = self._analyze_review_states(reviews)
                
                processed_prs.append({
                    "number": pr["number"],
                    "title": pr["title"],
                    "author": pr["user"]["login"],
                    "url": pr["html_url"],
                    "state": pr["state"],
                    "draft": pr.get("draft", False),
                    "created_at": pr["created_at"],
                    "updated_at": pr["updated_at"],
                    "review_summary": review_summary
                })

            # Build pagination info
            has_next = len(prs) > max_results if prs else False

            return {
                "data": processed_prs,
                "pagination": {
                    "current_page": 1,
                    "has_next_page": has_next,
                    "per_page": max_results,
                    "total_count": len(prs) if prs else 0
                }
            }

        except Exception as e:
            logging.error(f"Error searching pull requests: {e}")
            raise

    async def get_pull_request_reviews(self, owner: str, repo: str,
                                      pr_number: int) -> Dict[str, Any]:
        """
        Get comprehensive review analysis for specific PR.

        Preserves complex review state logic from gh-pulls-summary:
        - Latest review state per user
        - Handles approval → changes → approval flows
        """
        try:
            # Fetch reviews
            reviews = self.client.fetch_reviews(owner, repo, pr_number)

            if not reviews:
                return {
                    "pr_number": pr_number,
                    "approved_by": [],
                    "changes_requested_by": [],
                    "changes_requested_count": 0,
                    "approval_count": 0,
                    "review_timeline": []
                }

            # Apply the critical review state logic from gh-pulls-summary
            analysis = self._analyze_review_states(reviews)

            # Build detailed timeline
            timeline = []
            for review in sorted(reviews, key=lambda r: r.get("submitted_at", "")):
                if review.get("submitted_at"):
                    timeline.append({
                        "user": review["user"]["login"],
                        "state": review["state"],
                        "submitted_at": review["submitted_at"],
                        "body": review.get("body", "")
                    })

            return {
                "pr_number": pr_number,
                "approved_by": analysis["approved_by"],
                "changes_requested_by": analysis["changes_requested_by"],
                "changes_requested_count": analysis["changes_requested_count"],
                "approval_count": analysis["approval_count"],
                "total_reviewers": analysis["total_reviewers"],
                "review_timeline": timeline
            }

        except Exception as e:
            logging.error(f"Error getting PR reviews: {e}")
            raise

    def _analyze_review_states(self, reviews: List[Dict[str, Any]]) -> Dict[str, Any]:
        """
        Analyze review states using the complex logic from gh-pulls-summary.

        Critical logic preserved from lines 508-527 of original code:
        - Maps to most recent review state per user
        - Handles approval → changes → approval transitions
        - Ignores COMMENTED reviews when user has substantive review state
        """
        if not reviews:
            return {
                "approved_by": [],
                "changes_requested_by": [],
                "changes_requested_count": 0,
                "approval_count": 0,
                "total_reviewers": 0
            }
        
        # Map to most recent review state per user (preserving original logic)
        user_latest_review = {}
        for review in reviews:
            user = review["user"]["login"]
            submitted_at = review.get("submitted_at")
            state = review["state"]

            # Only consider reviews with a submitted_at timestamp
            # (ignore pending, etc)
            if not submitted_at:
                continue

            # If user not seen or this review is newer, update
            if (user not in user_latest_review or
                    submitted_at > user_latest_review[user]["submitted_at"]):
                # If the new state is "COMMENTED" but the existing state is not
                # "COMMENTED", ignore this review
                if (user in user_latest_review and
                        user_latest_review[user]["state"] != "COMMENTED" and
                        state == "COMMENTED"):
                    continue
                user_latest_review[user] = {"state": state,
                                           "submitted_at": submitted_at}

        # Extract current states
        states = [data["state"] for data in user_latest_review.values()]
        approved_by = [user for user, data in user_latest_review.items()
                      if data["state"] == "APPROVED"]
        changes_requested_by = [user for user, data in user_latest_review.items()
                               if data["state"] == "CHANGES_REQUESTED"]

        return {
            "approved_by": approved_by,
            "changes_requested_by": changes_requested_by,
            "changes_requested_count": sum(1 for s in states if s == "CHANGES_REQUESTED"),
            "approval_count": sum(1 for s in states if s == "APPROVED"),
            "total_reviewers": len(user_latest_review)
        }

    async def get_pull_request_comments(self, owner: str, repo: str,
                                       pr_number: int,
                                       resolution_filter: str = "all") -> Dict[str, Any]:
        """
        Get all comments for specific PR with resolution filtering.

        Comments are either resolved or open (unresolved).
        """
        try:
            # Fetch both issue comments and review comments
            issue_comments = self.client.fetch_issue_comments(owner, repo,
                                                              pr_number)
            review_comments = self.client.fetch_pull_request_comments(
                owner, repo, pr_number)

            # Process comments
            all_comments = []

            # Add issue comments (these are general PR comments)
            for comment in issue_comments:
                all_comments.append({
                    "type": "issue_comment",
                    "id": comment["id"],
                    "user": comment["user"]["login"],
                    "body": comment["body"],
                    "created_at": comment["created_at"],
                    "updated_at": comment["updated_at"],
                    "url": comment["html_url"],
                    "resolved": False  # Issue comments don't have resolution
                })

            # Add review comments (these are line-specific comments)
            for comment in review_comments:
                resolved = (comment.get("resolved", False)
                           if "resolved" in comment else False)
                all_comments.append({
                    "type": "review_comment",
                    "id": comment["id"],
                    "user": comment["user"]["login"],
                    "body": comment["body"],
                    "created_at": comment["created_at"],
                    "updated_at": comment["updated_at"],
                    "url": comment["html_url"],
                    "path": comment.get("path"),
                    "line": comment.get("line"),
                    "resolved": resolved
                })

            # Apply resolution filter
            if resolution_filter == "open":
                filtered_comments = [c for c in all_comments if not c["resolved"]]
            elif resolution_filter == "resolved":
                filtered_comments = [c for c in all_comments if c["resolved"]]
            else:  # "all"
                filtered_comments = all_comments

            # Sort by creation time
            filtered_comments.sort(key=lambda c: c["created_at"])

            return {
                "pr_number": pr_number,
                "comments": filtered_comments,
                "total_comments": len(all_comments),
                "filtered_count": len(filtered_comments),
                "resolution_filter": resolution_filter
            }

        except Exception as e:
            logging.error(f"Error getting PR comments: {e}")
            raise
