# Generated By: Cursor (Claude)
"""
Tests for GitHub API client.
"""

import unittest
from unittest.mock import Mock, patch, MagicMock
import requests

import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..'))

from mcp_github_server.github_client import GitHubClient, GitHubAPIError, RateLimitError, NetworkError


class TestGitHubClient(unittest.TestCase):
    """Test GitHub API client functionality."""
    
    def setUp(self):
        self.client = GitHubClient(token="test-token")
    
    def test_client_initialization(self):
        """Test client initializes with correct settings."""
        self.assertEqual(self.client.base_url, "https://api.github.com")
        self.assertEqual(self.client.timeout, 30)
        self.assertEqual(self.client.rate_limit_delay, 1.0)
        self.assertIn("Bearer test-token", self.client.headers["Authorization"])
    
    @patch('requests.get')
    def test_successful_request(self, mock_get):
        """Test successful API request."""
        mock_response = Mock()
        mock_response.status_code = 200
        mock_response.json.return_value = [{"id": 1, "title": "Test PR"}]
        mock_get.return_value = mock_response
        
        result = self.client.request("/test", use_paging=False)
        
        self.assertEqual(result, [{"id": 1, "title": "Test PR"}])
        mock_get.assert_called_once()
    
    @patch('requests.get')
    def test_rate_limit_error(self, mock_get):
        """Test rate limit error handling."""
        mock_response = Mock()
        mock_response.status_code = 403
        mock_response.headers = {
            "X-RateLimit-Remaining": "0",
            "X-RateLimit-Reset": "1234567890"
        }
        mock_get.return_value = mock_response
        
        with self.assertRaises(RateLimitError):
            self.client.request("/test")
    
    @patch('requests.get')
    def test_network_error(self, mock_get):
        """Test network error handling."""
        mock_get.side_effect = requests.exceptions.ConnectionError("Connection failed")
        
        with self.assertRaises(NetworkError):
            self.client.request("/test")
    
    @patch('requests.get')
    def test_404_error(self, mock_get):
        """Test 404 error handling."""
        mock_response = Mock()
        mock_response.status_code = 404
        mock_response.text = "Not found"
        mock_get.return_value = mock_response
        
        with self.assertRaises(GitHubAPIError) as context:
            self.client.request("/test")
        
        self.assertEqual(context.exception.status_code, 404)


if __name__ == '__main__':
    unittest.main()